### ISSUE TITLE
'unicodeescape' codec can't decode bytes

### ISSUE THREAD

**Issue by cnuptak** [asciid/stepik_scanner#1]
![image](https://user-images.githubusercontent.com/19365687/82734872-59416f00-9d26-11ea-8e4a-5ddf5e3eb56c.png)

catch some error on windows.

**Comment by asciid** [comment]
It's a Windows-only bug.Works on my machine.
I will try to reproduce and fix it later. Bezbab,

**Comment by asciid** [comment]
I will try to build an update with `pyinstaller` tonight. Stay tuned.

**Comment by cnuptak** [comment]
big deal

**Comment by asciid** [comment]
IDK how but an issue can't be reproduced. Maybe your environment sucks and you are a dick.
